### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by acjay** [russiann/promise-sequencial#2]
It seems to me that a common use case would be that you have some operands in an array, and some operation of one parameter to call for each operand. You don't want to kick off a bunch of operations at once. Another API might be to think more in terms of [Bluebird.map](https://gorillalogic.com/blog/using-lambdas-with-bluebird-map/?utm_source=javascriptweekly&utm_medium=email), but with sequential concurrency. That would avoid the need to make the firing off of the Promise lazy by wrapping in a function.

Assuming that this were the major use case...

Perhaps it could take another parameter, which would be the max parallelism.

A variation on this would could be `mapAndApply`, which might expect an a array of argument arrays to an operation of higher arity.

**Comment by rubenspgcavalcante** [comment]
If I understood, the problem would be the number of promise registration calls in the stack, causing a memory problem? Maybe it can use a generator to freeze the registration and go further (.next() call) only after the promise resolution/fail, this way it will be a more lazily approach and don't consume to much memory.
All in all, I think the parallelism is not a problem here, because the concept of library itself is do chain the resolution of an array of promises sequentially, which the current one always will wait for the resolution of the previous promise, being a serialized approach.

**Comment by acjay** [comment]
Yeah, my point was just that there's spectrum between fire all off at once and strictly one at a time. I'm just throwing out an idea, not even a feature request. I saw this on Javascript Weekly, and thought, "Cool! I've done similar things in other languages".

**Comment by russiann** [comment]
The idea of using Generators it great! I had not realized that the functions registrations were being fired all at once. I'm not sure if the impact of using many functions (like thousands) can cause memory problems. But it's something to consider.

Thanks @acjay @rubenspgcavalcante !
